// <auto-generated />
namespace RestaurantBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FixReservationTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixReservationTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202408041856530_FixReservationTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
