// <auto-generated />
namespace RestaurantBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class HandleSomeChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HandleSomeChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202408042049147_HandleSomeChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
